### ISSUE TITLE
Kernal Error with Canopy Installation

### ISSUE THREAD

**Issue by cmiller8** [IRkernel/IRkernel#150]
I just installed the latest Enthought Canopy installation and followed the instructions to install and run IRkernel -- when I try to start an R kernel, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\html\base\handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    **kw)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.2.2785.win-x86_64\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Users\cmiller\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.2.2785.win-x86_64\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by DSfrmBkln** [comment]
I don't know if this is related, but I run windows, too, and I've been getting this error any time I try to use an R kernel in IPython 3.1.  (I'm on Anaconda)

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    **kw)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Program Files\Anaconda\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Program Files\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Program Files\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by cmiller8** [comment]
Canopy also installed IPython 3.1.0-2 on my Windows 7 machine

**Comment by takluyver** [comment]
Is R on your system path? i.e. can you run `R` from a command line and get into an R prompt.

**Comment by DSfrmBkln** [comment]
Ah.  Silly me.  I was editing my path variable a while ago and I must have deleted the entry for R.  Problem solved on my end.  Many thanks!

**Comment by flying-sheep** [comment]
great :smile:
