### ISSUE TITLE
Kernel Error with Anaconda Installation

### ISSUE THREAD

**Issue by cmiller8** [IRkernel/IRkernel#152]
I had an issue yesterday with a Canopy installation. The other user fixed his through an Anaconda install and by having R set in their PATH. I have uninstalled Canopy and installed Anaconda and added R to my PATH such that the R prompt starts with the `R` command from the command line. 

But.... I'm still getting this error when I start a notebook with the R kernel:

```
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Anaconda\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Anaconda\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Anaconda\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Anaconda\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    **kw)
  File "C:\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I have also tried installing `rpy2` and go the exact error described in [this SE question](http://stackoverflow.com/questions/4924917/trouble-installing-rpy2-on-win7-r-2-12-python-2-5). I was able to solve that issue by installing `rpy2` using `conda` as shown in [this answer](http://stackoverflow.com/a/29193493/655733)

**Comment by takluyver** [comment]
Check `os.environ['PATH']` from a Python notebook. That error means that it's not finding `R` on the path.

**Comment by takluyver** [comment]
You could also try installing R and IRkernel using conda; that may work more smoothly.

http://continuum.io/blog/preliminary-support-R-conda

**Comment by cmiller8** [comment]
I uninstalled `R 3.2.0` and [reinstalled using `conda` ](http://continuum.io/conda-for-R) and it works now. At first, the kernel was crashing quite a bit until I updated the `R` packages as outlined in this project.

**Comment by takluyver** [comment]
OK, great. There's nothing I know how to do to make this more reliable within IRkernel, so closing this issue.
