### ISSUE TITLE
Kernel Error for R in jupyter

### ISSUE THREAD

**Issue by piltu007** [IRkernel/IRkernel#160]
Hi,
I have installed IRkernel as it was said in the readme file on my Windows 8.1PC. I followed every process which was said. After the installation when I started run the R kernel using jupyter notebook, it is giving me kernel error. The error is following:

'Traceback (most recent call last):
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 394, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    **kw)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Subhajit\Anaconda\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Subhajit\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\Subhajit\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified'

Please help me with this error.

**Comment by takluyver** [comment]
R on Windows doesn't install into PATH. See #159 and #152 for more info.

**Comment by piltu007** [comment]
I have reinstalled R using 'conda'. Now, I am getting a dead kernel for R. The error is: 'Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called 'stringi'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>, Execution halted'.

**Comment by takluyver** [comment]
We don't depend on stringi (as far as I know), but maybe one of our dependencies does, and the conda package isn't declaring that properly (@asmeurer might have better ideas than me).

Try installing `r-stringi` with conda.

**Comment by piltu007** [comment]
Thanks it worked.
