### ISSUE TITLE
Unable to install - ImportError: No module named ipython_genutils

### ISSUE THREAD

**Issue by abhishiv** [IRkernel/IRkernel#179]
While doing `IRkernel::installspec()` it throws up the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/Library/Python/2.7/site-packages/IPython/__init__.py", line 47, in <module>
    from .core.application import Application
  File "/Library/Python/2.7/site-packages/IPython/core/application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/Library/Python/2.7/site-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/Library/Python/2.7/site-packages/traitlets/traitlets.py", line 56, in <module>
    from ipython_genutils import py3compat
ImportError: No module named ipython_genutils
```

Running on Mac OS 10.9 using R version 3.2.1

**Comment by abhishiv** [comment]
Fixed, was actually some conflict between different versions of pythons.
