### ISSUE TITLE
UTF8 Encoding error (probably)

### ISSUE THREAD

**Issue by xavierfontaine** [IRkernel/IRkernel#181]
I am trying to have Jupyter running with an R kernel on Windows. Jupyter works fine with an IPython kernel: opening `ipython notebook`, I can properly create a new > notebooks > Python 2 and run code. 

Now when I try to create a new > notebooks > R, a notebook opens as expected, but I can't run code. The kernel appears to be busy from the very start, and remains stuck in this state.

On the shell, `ipython notebook` says the following:
    
    [I 16:57:16.128 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mat
    hjax/latest/MathJax.js
    [I 16:57:16.158 NotebookApp] The port 8888 is already in use, trying another ran
    dom port.
    [I 16:57:16.158 NotebookApp] Serving notebooks from local directory: C:\Anaconda
    \pkgs
    [I 16:57:16.158 NotebookApp] 0 active kernels
    [I 16:57:16.158 NotebookApp] The IPython Notebook is running at: http://localhos
    t:8889/
    [I 16:57:16.158 NotebookApp] Use Control-C to stop this server and shut down all
     kernels (twice to skip confirmation).
    [I 16:57:23.400 NotebookApp] Creating new notebook in
    [E 16:57:24.395 NotebookApp] Unhandled error in API request
        Traceback (most recent call last):
          File "C:\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 3
    94, in wrapper
            result = yield gen.maybe_future(method(self, *args, **kwargs))
          File "C:\Anaconda\lib\site-packages\IPython\html\services\sessions\handler
    s.py", line 53, in post
            model = sm.create_session(path=path, kernel_name=kernel_name)
          File "C:\Anaconda\lib\site-packages\IPython\html\services\sessions\session
    manager.py", line 66, in create_session
            kernel_name=kernel_name)
          File "C:\Anaconda\lib\site-packages\IPython\html\services\kernels\kernelma
    nager.py", line 84, in start_kernel
            kernel_name=kernel_name, **kwargs)
          File "C:\Anaconda\lib\site-packages\IPython\kernel\multikernelmanager.py",
     line 112, in start_kernel
            km.start_kernel(**kwargs)
          File "C:\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 240,
    in start_kernel
            **kw)
          File "C:\Anaconda\lib\site-packages\IPython\kernel\manager.py", line 189,
    in _launch_kernel
            return launch_kernel(kernel_cmd, **kw)
          File "C:\Anaconda\lib\site-packages\IPython\kernel\launcher.py", line 202,
     in launch_kernel
            proc = Popen(cmd, **kwargs)
          File "C:\Anaconda\lib\subprocess.py", line 710, in __init__
            errread, errwrite)
          File "C:\Anaconda\lib\subprocess.py", line 958, in _execute_child
            startupinfo)
        'WindowsError: [Error 2] Le fichier sp\xe9cifi\xe9 est introuvable'
    [E 16:57:24.410 NotebookApp] Uncaught exception POST /api/sessions (::1)
        HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri
    ='/api/sessions', version='HTTP/1.1', remote_ip='::1', headers={'Content-Length'
    : '71', 'Accept-Language': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encodi
    ng': 'gzip, deflate', 'Host': 'localhost:8889', 'Accept': 'application/json, tex
    t/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; r
    v:40.0) Gecko/20100101 Firefox/40.0', 'Connection': 'keep-alive', 'X-Requested-W
    ith': 'XMLHttpRequest', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Refe
    rer': 'http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=ir', 'Content-
    Type': 'application/json; charset=UTF-8'})
        Traceback (most recent call last):
          File "C:\Anaconda\lib\site-packages\tornado\web.py", line 1415, in _execut
    e
            result = yield result
          File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 870, in run
            value = future.result()
          File "C:\Anaconda\lib\site-packages\tornado\concurrent.py", line 215, in r
    esult
            raise_exc_info(self._exc_info)
          File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 230, in wrapper
            yielded = next(result)
          File "C:\Anaconda\lib\site-packages\IPython\html\base\handlers.py", line 4
    12, in wrapper
            self.finish(json.dumps(reply))
          File "C:\Anaconda\lib\json\__init__.py", line 243, in dumps
            return _default_encoder.encode(obj)
          File "C:\Anaconda\lib\json\encoder.py", line 207, in encode
            chunks = self.iterencode(o, _one_shot=True)
          File "C:\Anaconda\lib\json\encoder.py", line 270, in iterencode
            return _iterencode(o, 0)
        UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1360: in
    valid continuation byte
    [E 16:57:24.431 NotebookApp] {
          "Content-Length": "71",
          "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
          "Accept-Encoding": "gzip, deflate",
          "Connection": "keep-alive",
          "Accept": "application/json, text/javascript, */*; q=0.01",
          "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101
     Firefox/40.0",
          "Host": "localhost:8889",
          "X-Requested-With": "XMLHttpRequest",
          "Pragma": "no-cache",
          "Cache-Control": "no-cache",
          "Referer": "http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=ir"
    ,
          "Content-Type": "application/json; charset=UTF-8"
        }
    [E 16:57:24.437 NotebookApp] 500 POST /api/sessions (::1) 74.00ms referer=http:/
    /localhost:8889/notebooks/Untitled.ipynb?kernel_name=ir

The error, starting at `Unhandled error in API request`, does not occur with the Python kernel.

I believe there is an encoding problem, but I cannot see exactly where. I tried to modify my .Rprofile to have R use an UTF-8 encoding, by adding `Sys.setlocale(category = "LC_ALL", locale = "French_France.1252")`, but it didn't help.
I don't know whether this is releated to IRkernel or Jupyter... Any clue?

My configuration:  
- Windows 7  
- iPython (incl. notebook) and Anaconda version 3.2.0  
- R 3.2.1. I followed the instructions from [irkernel's github repo](http://irkernel.github.io/).  
- Works neither on IE nor on Firefox  

Many thanks in advance

**Comment by takluyver** [comment]
Which Python version did you install Anaconda with? If it's Python 2.7, can you try with Python 3.4?

**Comment by xavierfontaine** [comment]
Hi Thomas, many thanks for your reply.

This was with Python 2.7. I have just tried with Python 3.4. I also get an error. This time, the notebook GUI tells me that there is a kernel error. If I click on the error button, I see "failed to start the kernel", "Unkown server error" and the following:
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\html\base\handlers.py", line 394, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "C:\Anaconda3\lib\site-packages\IPython\html\services\kernels\kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "C:\Anaconda3\lib\site-packages\IPython\kernel\multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py", line 240, in start_kernel
    **kw)
  File "C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda3\lib\site-packages\IPython\kernel\launcher.py", line 202, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda3\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```
Where the last line means "the file cannot be found".

And the console says
```
C:\>ipython notebook
[I 11:32:45.167 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mat
hjax/latest/MathJax.js
[I 11:32:45.260 NotebookApp] Serving notebooks from local directory: C:\
[I 11:32:45.260 NotebookApp] 0 active kernels
[I 11:32:45.260 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 11:32:45.260 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[W 11:32:49.414 NotebookApp] C:\System Volume Information doesn't exist
[W 11:33:15.698 NotebookApp] C:\System Volume Information doesn't exist
[I 11:33:18.816 NotebookApp] Creating new notebook in
[E 11:33:21.595 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\IPython\html\base\handlers.py", line
394, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\handle
rs.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\sessions\sessio
nmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\Anaconda3\lib\site-packages\IPython\html\services\kernels\kernelm
anager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\multikernelmanager.py"
, line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py", line 240,
 in start_kernel
        **kw)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\manager.py", line 189,
 in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Anaconda3\lib\site-packages\IPython\kernel\launcher.py", line 202
, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Anaconda3\lib\subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "C:\Anaconda3\lib\subprocess.py", line 1112, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
[E 11:33:21.609 NotebookApp] {
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101
 Firefox/40.0",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Cache-Control": "no-cache",
      "Pragma": "no-cache",
      "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
      "Content-Length": "71",
      "Accept-Encoding": "gzip, deflate",
      "Host": "localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=ir"
,
      "Content-Type": "application/json; charset=UTF-8"
    }
[E 11:33:21.614 NotebookApp] 500 POST /api/sessions (::1) 279.00ms referer=http:
//localhost:8888/notebooks/Untitled.ipynb?kernel_name=ir
```

Any clue?

**Comment by takluyver** [comment]
Ah, OK. Now that the confusing extra error about unicode is gone, it looks like the real error all along was that it can't find R.

We should have a fix for this in master. Can you try installing from master:

```R
library(devtools)  # You may need to install devtools first
install_github('IRkernel/IRkernel')
IRkernel::installspec()
```

**Comment by xavierfontaine** [comment]
Following your advice, I installed IRkernel from Github, and now Jupyter works just fine with R.

Many thanks for your help Thomas!

**Comment by flying-sheep** [comment]
great!

**Comment by takluyver** [comment]
Excellent, that means that the fix works with Windows too. @flying-sheep , we should start thinking about doing a new release of IRkernel with the fix.
