### ISSUE TITLE
viz. with rbokeh crashes the kernel

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#194]
I try the following lines of code but I crash the kernel & I  get the error below.

Did I miss something (e.g. the libraries are in the user space...)? 

Code:
````
library(rbokeh)
 figure() %>% ly_points(cars$speed, cars$dist)
````
Error:

````
Traceback (most recent call last):
  File "/Users/e/anaconda/lib/python3.4/site-packages/notebook/base/handlers.py", line 436, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/e/anaconda/lib/python3.4/site-packages/notebook/services/sessions/handlers.py", line 56, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/Users/e/anaconda/lib/python3.4/site-packages/notebook/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/Users/e/anaconda/lib/python3.4/site-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
    **kwargs)
  File "/Users/e/anaconda/lib/python3.4/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/e/anaconda/lib/python3.4/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    **kw)
  File "/Users/e/anaconda/lib/python3.4/site-packages/jupyter_client/manager.py", line 186, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/e/anaconda/lib/python3.4/site-packages/jupyter_client/launcher.py", line 119, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/e/anaconda/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/Users/e/anaconda/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

````

**Comment by takluyver** [comment]
That looks like an error starting the kernel, I don't think you'd get a Python error like that if the kernel started OK and then crashed.

In a Python notebook, what happens if you run: `!R --version`

**Comment by smartinsightsfromdata** [comment]
Apologies: my system was messed up.  I will close this and open a new issue (as there is not crash).

Thanks for your patience
