### ISSUE TITLE
IRkernel::installspec() gives ... undefined symbol: zmq_msg_gets error

### ISSUE THREAD

**Issue by langusta** [IRkernel/IRkernel#212]
Hi,
I'm trying to install R kernel for jupyter that I have installed with Anaconda. When I call the `IRkernel::installspec()` i get following error:
```R
> IRkernel::installspec()
Traceback (most recent call last):
  File "/home/user/Programy/Anaconda/bin/jupyter-kernelspec", line 2, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/user/Programy/Anaconda/lib/python3.5/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/user/Programy/Anaconda/lib/python3.5/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/home/user/Programy/Anaconda/lib/python3.5/site-packages/zmq/__init__.py", line 70, in <module>
    from zmq import devices
  File "/home/user/Programy/Anaconda/lib/python3.5/site-packages/zmq/devices/__init__.py", line 7, in <module>
    from zmq.devices import basedevice, proxydevice, monitoredqueue, monitoredqueuedevice
  File "zmq/backend/cython/context.pxd", line 26, in init zmq.devices.monitoredqueue (zmq/devices/monitoredqueue.c:4455)
  File "/home/user/Programy/Anaconda/lib/python3.5/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/user/Programy/Anaconda/lib/python3.5/site-packages/zmq/backend/cython/message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: zmq_msg_gets
```
My session info:
```R
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=pl_PL.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    IRdisplay_0.3   tools_3.2.2     base64enc_0.1-3
 [5] uuid_0.1-2      stringi_0.5-2   rzmq_0.7.7      IRkernel_0.5   
 [9] jsonlite_0.9.17 stringr_1.0.0   digest_0.6.8    repr_0.4       
[13] evaluate_0.8  
```
I can't find any solution on the internet :( I would be grateful for help!

**Comment by karldw** [comment]
I have the same issue, running Python 3.4 in an Anaconda environment on Ubuntu 15.10.  The error I encountered, slightly different from the original post, is:
```python
> IRkernel::installspec()
Traceback (most recent call last):
  File "/home/karl/.conda/envs/my34/bin/jupyter-kernelspec", line 2, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/message.cpython-34m.so: undefined symbol: zmq_msg_gets
```

The error is the same with the "development" and "source" versions of `repr`, `IRdisplay` and `IRkernel`.

It looks like there might be trouble importing `zmq`, but I can run this code without trouble:
```python
$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zmq import backend
```

Like @langusta, I'd be very grateful for help.

**Comment by takluyver** [comment]
@minrk, any thoughts? Has conda got mismatching pyzmq and zmq?

**Comment by minrk** [comment]
What's `conda list`? Also what do you get for `find / -name 'libzmq*.so*'`? I think you are right that this is pyzmq loading a different libzmq than it's compiled against, but I'm not sure why the R case and Python would end up loading different versions, though. Can you share the environment in both cases (from R and Python APIs, in case something funny is happening at startup, which I have seen happen with conda Python on OS X).

**Comment by langusta** [comment]
The output of `conda list` (is there a way to add a scrollbar to this?):
```
# packages in environment at /home/user/Programy/Anaconda:
#
abstract-rendering        0.5.1               np110py35_0  
alabaster                 0.7.6                    py35_0  
anaconda                  2.4.0               np110py35_0  
anaconda-client           1.1.0                    py35_0  
argcomplete               1.0.0                    py35_1  
astropy                   1.0.5               np110py35_1  
babel                     2.1.1                    py35_0  
beautifulsoup4            4.4.1                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py35_0  
bokeh                     0.10.0                   py35_0  
boto                      2.38.0                   py35_0  
cffi                      1.2.1                    py35_0  
clyent                    0.4.0                    py35_0  
colorama                  0.3.3                    py35_0  
conda                     3.18.3                   py35_0  
conda-build               1.18.1                   py35_0  
conda-env                 2.4.4                    py35_0  
configobj                 5.0.6                    py35_0  
cryptography              1.0.2                    py35_0  
curl                      7.45.0                        0  
cython                    0.23.4                   py35_0  
cytoolz                   0.7.4                    py35_0  
datashape                 0.4.7               np110py35_1  
decorator                 4.0.4                    py35_0  
docutils                  0.12                     py35_0  
fastcache                 1.0.2                    py35_0  
flask                     0.10.1                   py35_1  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
greenlet                  0.4.9                    py35_0  
h5py                      2.5.0               np110py35_4  
hdf5                      1.8.15.1                      2  
idna                      2.0                      py35_0  
ipykernel                 4.1.1                    py35_0  
ipython                   4.0.0                    py35_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_0  
ipython-qtconsole         4.0.1                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                4.1.0                    py35_0  
itsdangerous              0.24                     py35_0  
jdcal                     1.0                      py35_0  
jedi                      0.9.0                    py35_0  
jinja2                    2.8                      py35_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py35_0  
jupyter                   1.0.0                    py35_0  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0  
jupyter_console           4.0.3                    py35_0  
jupyter_core              4.0.6                    py35_0  
libffi                    3.0.13                        0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
lxml                      3.4.4                    py35_0  
markupsafe                0.23                     py35_0  
matplotlib                1.4.3               np110py35_2  
mistune                   0.7.1                    py35_0  
multipledispatch          0.4.8                    py35_0  
nbconvert                 4.0.0                    py35_0  
nbformat                  4.0.1                    py35_0  
networkx                  1.10                     py35_0  
nltk                      3.1                      py35_0  
nose                      1.3.7                    py35_0  
notebook                  4.0.6                    py35_0  
numexpr                   2.4.4               np110py35_0  
numpy                     1.10.1                   py35_0  
odo                       0.3.4                    py35_0  
openblas                  0.2.14                        3  
openpyxl                  2.2.6                    py35_0  
openssl                   1.0.2d                        0  
pandas                    0.17.0              np110py35_0  
patchelf                  0.6                           0  
path.py                   8.1.2                    py35_0  
patsy                     0.4.0               np110py35_0  
pep8                      1.6.2                    py35_0  
pexpect                   3.3                      py35_0  
pickleshare               0.5                      py35_0  
pillow                    3.0.0                    py35_1  
pip                       7.1.2                    py35_0  
ply                       3.8                      py35_0  
psutil                    3.2.2                    py35_0  
ptyprocess                0.5                      py35_0  
py                        1.4.30                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_0  
pycparser                 2.14                     py35_0  
pycrypto                  2.6.1                    py35_0  
pycurl                    7.19.5.1                 py35_3  
pyflakes                  1.0.0                    py35_0  
pygments                  2.0.2                    py35_0  
pyopenssl                 0.15.1                   py35_1  
pyparsing                 2.0.3                    py35_0  
pyqt                      4.11.4                   py35_0  
pytables                  3.2.2               np110py35_0  
pytest                    2.8.1                    py35_0  
python                    3.5.0                         1  
python-dateutil           2.4.2                    py35_0  
pytz                      2015.6                   py35_0  
pyyaml                    3.11                     py35_1  
pyzmq                     14.7.0                   py35_1  
qt                        4.8.7                         1  
qtconsole                 4.1.0                    py35_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py35_0  
requests                  2.8.1                    py35_0  
rope                      0.9.4                    py35_1  
rope-py3k-0.9.4           1                         <pip>
scikit-image              0.11.3              np110py35_0  
scikit-learn              0.16.1              np110py35_0  
scipy                     0.16.0              np110py35_1  
setuptools                18.4                     py35_0  
simplegeneric             0.8.1                    py35_0  
sip                       4.16.9                   py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.0                    py35_0  
sockjs-tornado            1.0.1                    py35_0  
sphinx                    1.3.1                    py35_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py35_0  
spyder                    2.3.7                    py35_1  
spyder-app                2.3.7                    py35_0  
sqlalchemy                1.0.9                    py35_0  
sqlite                    3.8.4.1                       1  
statsmodels               0.6.1               np110py35_0  
sympy                     0.7.6.1                  py35_0  
tables                    3.2.2                     <pip>
terminado                 0.5                      py35_1  
theano                    0.7.0               np110py35_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py35_0  
tornado                   4.2.1                    py35_1  
traitlets                 4.0.0                    py35_0  
ujson                     1.33                     py35_0  
unicodecsv                0.14.1                   py35_0  
util-linux                2.21                          0  
werkzeug                  0.10.4                   py35_0  
wheel                     0.26.0                   py35_1  
xlrd                      0.9.4                    py35_0  
xlsxwriter                0.7.7                    py35_0  
xlwt                      1.0.0                    py35_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  
```

The output of `find / -name 'libzmq*.so*'`:
```
/home/user/Programy/Anaconda/pkgs/zeromq-4.1.3-0/lib/libzmq.so
/home/user/Programy/Anaconda/pkgs/zeromq-4.1.3-0/lib/libzmq.so.5.0.0
/home/user/Programy/Anaconda/pkgs/zeromq-4.1.3-0/lib/libzmq.so.5
/home/user/Programy/Anaconda/lib/libzmq.so
/home/user/Programy/Anaconda/lib/libzmq.so.5.0.0
/home/user/Programy/Anaconda/lib/libzmq.so.5
/usr/lib/x86_64-linux-gnu/libzmq.so
/usr/lib/x86_64-linux-gnu/libzmq.so.3.1.0
/usr/lib/x86_64-linux-gnu/libzmq.so.3
```

Python:
```
user@computor:~/Programy$ python
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zmq import backend
>>> import IPython
>>> print(IPython.sys_info())
{'commit_hash': 'f534027',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/user/Programy/Anaconda/lib/python3.5/site-packages/IPython',
 'ipython_version': '4.0.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-63-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/user/Programy/Anaconda/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, '
                '21:57:25) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

R:
```
user@computor:~/Programy$ R

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R jest oprogramowaniem darmowym i dostarczany jest BEZ JAKIEJKOLWIEK GWARANCJI.
Możesz go rozpowszechniać pod pewnymi warunkami.
Wpisz 'license()' lub 'licence()' aby uzyskać szczegóły dystrybucji.

R jest projektem kolaboracyjnym z wieloma uczestnikami.
Wpisz 'contributors()' aby uzyskać więcej informacji oraz
'citation()' aby dowiedzieć się jak cytować R lub pakiety R w publikacjach.

Wpisz 'demo()' aby zobaczyć demo, 'help()' aby uzyskać pomoc on-line, lub
'help.start()' aby uzyskać pomoc w przeglądarce HTML.
Wpisz 'q()' aby wyjść z R.

> library(IRkernel)
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=pl_PL.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] IRkernel_0.5

loaded via a namespace (and not attached):
 [1] magrittr_1.5    IRdisplay_0.3   tools_3.2.2     base64enc_0.1-3
 [5] uuid_0.1-2      stringi_0.5-2   rzmq_0.7.7      jsonlite_0.9.17
 [9] stringr_1.0.0   digest_0.6.8    repr_0.4        evaluate_0.8 
```

**Comment by karldw** [comment]
The output of `conda list`:
(I made a new conda environment, `test_ir`, to cut down on the number of packages. The problem is the same as it was for my original environment.)

```
# packages in environment at /home/karl/.conda/envs/test_ir:
#
decorator                 4.0.4                    py34_0  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
ipykernel                 4.1.1                    py34_0  
ipython                   4.0.0                    py34_0  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py34_0  
ipywidgets                4.1.0                    py34_0  
jinja2                    2.8                      py34_0  
jsonschema                2.4.0                    py34_0  
jupyter                   1.0.0                    py34_0  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py34_0  
jupyter_console           4.0.3                    py34_0  
jupyter_core              4.0.6                    py34_0  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libxml2                   2.9.2                         0  
markupsafe                0.23                     py34_0  
mistune                   0.7.1                    py34_0  
nbconvert                 4.0.0                    py34_0  
nbformat                  4.0.1                    py34_0  
notebook                  4.0.6                    py34_0  
openssl                   1.0.2d                        0  
path.py                   8.1.2                    py34_0  
pexpect                   3.3                      py34_0  
pickleshare               0.5                      py34_0  
pip                       7.1.2                    py34_0  
ptyprocess                0.5                      py34_0  
pygments                  2.0.2                    py34_0  
pyqt                      4.11.4                   py34_0  
python                    3.4.3                         2  
pyzmq                     14.7.0                   py34_1  
qt                        4.8.7                         1  
qtconsole                 4.1.0                    py34_0  
readline                  6.2                           2  
setuptools                18.4                     py34_0  
simplegeneric             0.8.1                    py34_0  
sip                       4.16.9                   py34_0  
sqlite                    3.8.4.1                       1  
terminado                 0.5                      py34_1  
tk                        8.5.18                        0  
tornado                   4.2.1                    py34_1  
traitlets                 4.0.0                    py34_0  
wheel                     0.26.0                   py34_1  
xz                        5.0.5                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  
```



The output of `find / -name 'libzmq*.so*'`:
```bash
/home/karl/.conda/envs/.pkgs/zeromq-4.1.3-0/lib/libzmq.so
/home/karl/.conda/envs/.pkgs/zeromq-4.1.3-0/lib/libzmq.so.5
/home/karl/.conda/envs/.pkgs/zeromq-4.1.3-0/lib/libzmq.so.5.0.0
/home/karl/.conda/envs/test_ir/lib/libzmq.so
/home/karl/.conda/envs/test_ir/lib/libzmq.so.5
/home/karl/.conda/envs/test_ir/lib/libzmq.so.5.0.0
/usr/lib/x86_64-linux-gnu/libzmq.so.3.1.0
/usr/lib/x86_64-linux-gnu/libzmq.so
/usr/lib/x86_64-linux-gnu/libzmq.so.3
```


Python:
```python
$ python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import IPython
>>> print(IPython.sys_info())
{'commit_hash': 'f534027',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/karl/.conda/envs/test_ir/lib/python3.4/site-packages/IPython',
 'ipython_version': '4.0.0',
 'os_name': 'posix',
 'platform': 'Linux-4.2.0-17-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/karl/.conda/envs/test_ir/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 |Continuum Analytics, Inc.| (default, Oct 19 2015, '
                '21:52:17) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}


```



R:
```R
$ R

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(IRkernel)
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] IRkernel_0.5

loaded via a namespace (and not attached):
 [1] magrittr_1.5         IRdisplay_0.3.0.9000 tools_3.2.2         
 [4] base64enc_0.1-3      uuid_0.1-2           stringi_1.0-1       
 [7] rzmq_0.7.7           jsonlite_0.9.17      stringr_1.0.0       
[10] digest_0.6.8         repr_0.4             evaluate_0.8        

```

**Comment by minrk** [comment]
And can you show your ENV variables, as well? Also, what do you see from

    ldd /home/karl/.conda/envs/test_ir/lib/libzmq.so

?

**Comment by karldw** [comment]
Here are the environment variables that might be relevant:

```bash
$ printenv
SHELL=/bin/bash
USER=karl
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PATH=/home/karl/.conda/envs/test_ir/bin:/home/karl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LANG=en_US.UTF-8
GDM_LANG=en_US
HOME=/home/karl
SHLVL=1
LANGUAGE=en_US
CONDA_ENV_PATH=/home/karl/.conda/envs/test_ir
LOGNAME=karl
CONDA_DEFAULT_ENV=test_ir
```


And the output of `ldd`:
```bash
$ ldd /home/karl/.conda/envs/test_ir/lib/libzmq.so
	linux-vdso.so.1 =>  (0x00007ffef176a000)
	libsodium.so.13 => /home/karl/.conda/envs/test_ir/lib/./libsodium.so.13 (0x00007fc5e7368000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc5e713e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc5e6f1f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc5e6b9d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc5e6895000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc5e64ca000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc5e62b3000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557f65c61000)
```

**Comment by minrk** [comment]
And what about `ldd /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/message.cpython-34m.so`?

**Comment by karldw** [comment]
```bash
$ ldd /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/message.cpython-34m.so
	linux-vdso.so.1 =>  (0x00007ffd741e5000)
	libzmq.so => /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/../../../../../libzmq.so (0x00007fd878dd8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd878bad000)
	libpython3.4m.so.1.0 => /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/../../../../../libpython3.4m.so.1.0 (0x00007fd878702000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd8784e4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd87811a000)
	libsodium.so.13 => /home/karl/.conda/envs/my34/lib/python3.4/site-packages/zmq/backend/cython/../../../../.././libsodium.so.13 (0x00007fd877ec3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd877b41000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd877838000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd877621000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd87741d000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fd877219000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f7761e4000)
```

**Comment by dswalter** [comment]
I'm having the same issue. Has this been resolved?

**Comment by flying-sheep** [comment]
definitely not by us as it’s not our bug. we just give free tech support here :wink:

maybe we should close setup problems like this if the user doesn’t answer for a week. i don’t like this issue tracker being full of things only the user can fix.

**Comment by JanSchulz** [comment]
For me this whole thing looks like either the bindings for libzmq or the devs for the conda packages have some problems (aka libzmq/bindings removed a symbol and didn't bump the abi or conda didn't do a library transition/ rebuild the packages against the new lib). 

If so: add a new item in the readme so that we don't get any more issues? "if you have a conda env and a problem with libzmq: write the conda people to fix their stuff"?

**Comment by langusta** [comment]
I searched where to complain about this issue to Anaconda community and it turns out that they have "their own" R packages. When you install them R kernel becomes available in jupyter. I used the command from [here](https://www.continuum.io/blog/developer/jupyter-and-conda-r): 
```
conda install -c r r-essentials
```
and it works fine.

**Comment by dswalter** [comment]
I also ended up having to use a conda R installation, with "conda create -y -n my-py3r-env -c r r-essentials  python=3.4 zeromq=4.0*". 

By the way, thanks to those working on the IRkernel. I know open-source can be pretty thankless, so I just wanted to communicate my gratitude. :)

**Comment by flying-sheep** [comment]
aww thanks!

**Comment by langusta** [comment]
I'm also grateful for your hard work!

**Comment by flying-sheep** [comment]
:blush:

**Comment by karldw** [comment]
Agreed, thanks!
