### ISSUE TITLE
calling `vignette()` in a jupyter console crashes the console

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#328]
```
c:\data\external\R
λ jupyter console --kernel ir33
Jupyter Console 4.1.1
[...]
In [4]: vignette()

Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\jupyter-console-script.py", line 4, in <module>
    app.main()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\portabel\miniconda\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\app.py", line 152, in start
    self.shell.mainloop()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 483, in mainloop
    self.interact(display_banner=display_banner)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 659, in interact
    self.run_cell(source_raw)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 203, in run_cell
    self.handle_execute_reply(msg_id, timeout=0.05)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 231, in handle_execute_reply
    page.page(item['data']['text/plain'])
KeyError: 'data'
```

[Update: also reported upstream: https://github.com/jupyter/jupyter_console/issues/73]

**Comment by flying-sheep** [comment]
how does this happen? why is there no “data” key?

**Comment by janschulz** [comment]
Because it is sent as a page and a page seems not to have the usual data key? So the error seems to be on the other side?

**Comment by flying-sheep** [comment]
hmm, i fixed some stuff regarding this some time ago and `vignette()` works flawlessly. even opens a pager :smile:
