### ISSUE TITLE
Looking for R Kernel in wrong directory

### ISSUE THREAD

**Issue by jolespin** [IRkernel/IRkernel#335]
Once upon a time ago, I installed the conda suite in Dropbox but then Dropbox did me dirty so I installed it in a different directory.  Deleted everything and started new but somehow R is being called from the old directory.  

**What is calling the wrong `R` directory so I can go in and change it?**

My current R is:
`
    $ which R
    /Users/Mu/Sync/anaconda/bin/R
`
This is my error when I try to run an R kernel

```
    Traceback (most recent call last):
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 58, in post
        sm.create_session(path=path, kernel_name=kernel_name))
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "/Users/Mu/Sync/anaconda/lib/python3.5/subprocess.py", line 1544, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mu/Dropbox/anaconda/lib/R/bin/R'

```

**Comment by takluyver** [comment]
Run `jupyter kernelspec list` to see where kernel specs are stored. That contains the path to the R it was installed with. The easiest way to fix it is to run the final step of the IRKernel installation again:

```R
IRkernel::installspec()
```

**Comment by jolespin** [comment]
! That was such a quick fix. Thank you

**Comment by takluyver** [comment]
You're welcome
