### ISSUE TITLE
Unexpected dead kernel because of pbdZMQ package

### ISSUE THREAD

**Issue by aakhmetz** [IRkernel/IRkernel#403]
IRkernel of the latest version stopped working for me. It has that timeout message with no visible output and then simply a dead kernel. With one of my notebook, I got the following message:

> [I 02:00:34.017 NotebookApp] KernelRestarter: restarting kernel (1/5)
IRkernel::main()
[W 02:01:01.018 NotebookApp] Timeout waiting for kernel_info_reply: f92479d0-b71e-43ca-a2cb-fef91687dab5
[E 02:01:01.019 NotebookApp] Exception restarting kernel
    Traceback (most recent call last):
      File "/Users/andrei/anaconda/envs/rcore/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 88, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/Users/andrei/anaconda/envs/rcore/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/Users/andrei/anaconda/envs/rcore/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    tornado.gen.TimeoutError: Timeout waiting for restart
[E 02:01:01.057 NotebookApp] {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0",
      "Referer": "http://localhost:8888/notebooks/ESS16/src/Model-2_part1.ipynb",
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.5",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "0"
    }
[E 02:01:01.057 NotebookApp] 500 POST /api/kernels/f92479d0-b71e-43ca-a2cb-fef91687dab5/restart (::1) 30247.99ms referer=http://localhost:8888/notebooks/ESS16/src/Model-2_part1.ipynb
[I 02:01:01.850 NotebookApp] Kernel shutdown: f92479d0-b71e-43ca-a2cb-fef91687dab5

It worked a week ago and it still works with the old version of IRkernel available on conda-repo. 

**My configuration**
> R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin11.0.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

>locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>loaded via a namespace (and not attached):
[1] digest_0.6.10      withr_1.0.2        IRdisplay_0.4.9000 repr_0.9          
[5] R6_2.1.2           jsonlite_1.0       git2r_0.15.0       magrittr_1.5
[9] evaluate_0.9       httr_1.2.1         stringi_1.1.1      uuid_0.1-2
[13] curl_1.2           IRkernel_0.6       devtools_1.12.0    tools_3.3.1       
[17] stringr_1.0.0      memoise_1.0.0      pbdZMQ_0.2-3

Actually I have no idea why it happened

**Comment by aakhmetz** [comment]
So, I checked more precisely where I have an error. 

The problem appeared to be with **pbdZMQ** package. 

If I use a conda version of it and do the installation with the command:
``conda install -c r r-pbdzmq``
then everything is Ok.

If I install it within R-environment as it's recommended by installation guide:
``install.packages(c('pbdZMQ'))``
then I run into trouble and my IRkernel dies.

**Comment by flying-sheep** [comment]
you either have to follow our instructions, or follow other people’s instructions, and don’t mix&match.

we recommend `install.packages` for everything and `devtools::install_github` for the IRkernel.

if you use anaconda, you should install everything using anaconda.
