### ISSUE TITLE
Failure to run command 

### ISSUE THREAD

**Issue by rvino** [IRkernel/IRkernel#411]
I've installed IRkernel, but when I try to launch an R notebook this error appears and the notebook starts with a kernel error. I'm very sorry about this formatting! Any help would be very appreciated.

```
[E 18:02:31.628 NotebookApp] Failed to run command:
[u'/Users/rorypulvino/anaconda/lib/R/bin/R', u'--slave', u'-e', u'IRkernel::main()', u'--args',    u'/Users/rorypulvino/Library/Jupyter/runtime/kernel-390f18d0-15a7-4bc1-a467-83ef1036dab7.json']
            PATH='/Users/rorypulvino/anaconda2/bin:/Users/rorypulvino/anaconda2/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/rorypulvino/.rvm/gems/ruby-2.3.0/bin:/Users/rorypulvino/.rvm/gems/ruby-2.3.0@global/bin:/Users/rorypulvino/.rvm/rubies/ruby-2.3.0/bin:/Users/rorypulvino/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rorypulvino/.rvm/bin'
        with kwargs:
    {'cwd': u'/Users/rorypulvino', 'stdin': -1, 'preexec_fn': <function <lambda> at 0x10554f668>, 'stderr': None, 'stdout': None}
```

```
[E 18:02:31.642 NotebookApp] Unhandled error in API request
        Traceback (most recent call last):
          File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/Users/rorypulvino/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory`
`[E 18:02:31.648 NotebookApp] {
      "Origin": "http://localhost:8888", 
      "Content-Length": "72", 
      "Accept-Language": "en-US,en;q=0.8", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/notebooks/Untitled3.ipynb?kernel_name=ir", 
      "Content-Type": "application/json"
    }
[E 18:02:31.649 NotebookApp] 500 POST /api/sessions (::1) 79.68ms referer=http://localhost:8888/notebooks/Untitled3.ipynb?kernel_name=ir
```

I found this [post](https://github.com/jupyter/notebook/issues/1236) where the API issue was dealt with, but when I followed those steps the error still appears. Including all output from debugs and lists. I also saw this [post](https://github.com/jupyter/notebook/issues/300) dealing with a similar issue for python notebook, but wanted to first ask for alternative/known solutions before I tried something like `python -m IRkernel kernelspec install-self`. 

Output from `jupyter kernelspec list` which seems to show that the ir path is wrong, but I'm not really sure if that's right or how to reset it.
`jupyter kernelspec list
Available kernels:
  python2    /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
  ir         /Users/rorypulvino/Library/Jupyter/kernels/ir`

Running the debugs yielded this:

```
jupyter kernelspec list --debug
[ListKernelSpecs] Searching [u'/Users/rorypulvino', '/Users/rorypulvino/.jupyter', '/Users/rorypulvino/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ListKernelSpecs] Looking for jupyter_config in /etc/jupyter
[ListKernelSpecs] Looking for jupyter_config in /usr/local/etc/jupyter
[ListKernelSpecs] Looking for jupyter_config in /Users/rorypulvino/anaconda2/etc/jupyter
[ListKernelSpecs] Looking for jupyter_config in /Users/rorypulvino/.jupyter
[ListKernelSpecs] Looking for jupyter_config in /Users/rorypulvino
[ListKernelSpecs] Found kernel ir in /Users/rorypulvino/Library/Jupyter/kernels
[ListKernelSpecs] Native kernel (python2) available from /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
[ListKernelSpecs] Found kernel ir in /Users/rorypulvino/Library/Jupyter/kernels
[ListKernelSpecs] Native kernel (python2) available from /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
Available kernels:
  python2    /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
  ir         /Users/rorypulvino/Library/Jupyter/kernels/ir`
```

while the other debug yielded this

```
jupyter notebook --debug
[D 18:13:44.606 NotebookApp] Searching [u'/Users/rorypulvino', '/Users/rorypulvino/.jupyter', '/Users/rorypulvino/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 18:13:44.607 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 18:13:44.609 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 18:13:44.609 NotebookApp] Looking for jupyter_config in /Users/rorypulvino/anaconda2/etc/jupyter
[D 18:13:44.609 NotebookApp] Looking for jupyter_config in /Users/rorypulvino/.jupyter
[D 18:13:44.611 NotebookApp] Looking for jupyter_config in /Users/rorypulvino
[D 18:13:44.612 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 18:13:44.612 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 18:13:44.613 NotebookApp] Looking for jupyter_notebook_config in /Users/rorypulvino/anaconda2/etc/jupyter
[D 18:13:44.614 NotebookApp] Loaded config file: /Users/rorypulvino/anaconda2/etc/jupyter/jupyter_notebook_config.json
[D 18:13:44.615 NotebookApp] Looking for jupyter_notebook_config in /Users/rorypulvino/.jupyter
[D 18:13:44.615 NotebookApp] Looking for jupyter_notebook_config in /Users/rorypulvino
[D 18:13:44.625 NotebookApp] [nb_conda_kernels] refreshing conda info
[D 18:13:45.958 NotebookApp] [nb_conda_kernels] refreshing conda kernelspecs
[I 18:13:45.961 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 18:13:46.847 NotebookApp] The port 8888 is already in use, trying another port.
[I 18:13:46.975 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 18:13:46.975 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 18:13:46.985 NotebookApp] [nb_conda] enabled
[I 18:13:47.126 NotebookApp] [nb_anacondacloud] enabled
[I 18:13:47.135 NotebookApp] Serving notebooks from local directory: /Users/rorypulvino
[I 18:13:47.135 NotebookApp] 0 active kernels 
[I 18:13:47.135 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 18:13:47.135 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 18:13:47.698 NotebookApp] Using contents: services/contents
[D 18:13:47.767 NotebookApp] 200 GET /tree (::1) 70.29ms
[D 18:13:47.793 NotebookApp] 304 GET /custom/custom.css (::1) 4.19ms
[D 18:13:48.067 NotebookApp] 200 GET /static/services/contents.js?v=20160929181345 (::1) 2.77ms
[D 18:13:48.075 NotebookApp] 200 GET /custom/custom.js?v=20160929181345 (::1) 2.60ms
[D 18:13:48.122 NotebookApp] 200 GET /api/config/tree?_=1475162027926 (::1) 5.90ms
[D 18:13:48.127 NotebookApp] 200 GET /api/config/common?_=1475162027927 (::1) 3.56ms
[D 18:13:48.129 NotebookApp] 200 GET /api/terminals?_=1475162027928 (::1) 1.09ms
[D 18:13:48.132 NotebookApp] Found kernel ir in /Users/rorypulvino/Library/Jupyter/kernels
[D 18:13:48.137 NotebookApp] Native kernel (python2) available from /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
[D 18:13:48.138 NotebookApp] Found kernel ir in /Users/rorypulvino/Library/Jupyter/kernels
[D 18:13:48.138 NotebookApp] Native kernel (python2) available from /Users/rorypulvino/anaconda2/lib/python2.7/site-packages/ipykernel/resources
[D 18:13:48.142 NotebookApp] 304 GET /api/kernelspecs (::1) 11.24ms
[D 18:13:48.145 NotebookApp] 200 GET /api/terminals?_=1475162027930 (::1) 1.54ms
[D 18:13:48.148 NotebookApp] 200 GET /api/sessions?_=1475162027929 (::1) 1.86ms
[D 18:13:48.280 NotebookApp] 200 GET /api/contents?type=directory&_=1475162027931 (::1) 15.13ms
[D 18:13:48.283 NotebookApp] 200 GET /nbextensions/nb_conda/tree.js?v=20160929181345 (::1) 1.93ms
[D 18:13:48.363 NotebookApp] 200 GET /nbextensions/nb_conda/models.js?v=20160929181345 (::1) 6.28ms
[D 18:13:48.371 NotebookApp] 200 GET /nbextensions/nb_conda/urls.js?v=20160929181345 (::1) 5.46ms
[D 18:13:48.376 NotebookApp] 200 GET /nbextensions/nb_conda/views.js?v=20160929181345 (::1) 4.02ms
[D 18:13:48.389 NotebookApp] 200 GET /nbextensions/nb_conda/common.js?v=20160929181345 (::1) 3.02ms
[D 18:13:48.408 NotebookApp] 304 GET /nbextensions/nb_conda/conda.css (::1) 1.61ms
[D 18:13:48.413 NotebookApp] 304 GET /nbextensions/nb_conda/tab.html (::1) 1.56ms
```

**Comment by takluyver** [comment]
Does `/Users/rorypulvino/anaconda/lib/R/bin/R` exist, and can you run it?

**Comment by rvino** [comment]
Noo it does not. I had to reinstall anaconda recently and it's now anaconda2, which does not have a `lib/R/bin/R`

**Comment by rvino** [comment]
I solved most of the issue thanks to takluyver's question. I went into the `anaconda2/lib/R/bin/R` and ran it and from there installed the kernel following the directions from the install site. I can now run IRkernel notebooks without error.

**Comment by takluyver** [comment]
Great. Yes, the kernelspec includes the absolute path to the R interpreter, so if it changes, you need to run `IRkernel::installspec()` again.
