### ISSUE TITLE
R and package help

### ISSUE THREAD

**Issue by izahn** [IRkernel/IRkernel#422]
I'm not sure if this is a bug, missing feature, or problem in my end, but 

``` r
help(package = "stats")
```

produces nothing, and 
``` r
help.start()
```

produces a message about "the browser launched by '/usr/bin/xdg-open'..." but does not open the help page.

**Comment by takluyver** [comment]
Are your IRkernel packages (IRkernel, IRdisplay, repr) up to date? `help(package = "stats")` works for me, though I see something similar with `help.start()`.

**Comment by izahn** [comment]
My packages were close to up to date. I installed the github ones again just to be sure, and `help(package = "stats")` still didn't work for me. Here is my `sessionsInfo()`:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] R6_2.2.0           magrittr_1.5       IRdisplay_0.4.9000 pbdZMQ_0.2-4      
 [5] tools_3.3.2        crayon_1.3.2       uuid_0.1-2         stringi_1.1.2     
 [9] IRkernel_0.7       jsonlite_1.1       stringr_1.1.0      digest_0.6.10     
[13] repr_0.9.9000      evaluate_0.10
```

**Comment by izahn** [comment]
Maybe related: `library()` also doesn't produce any output on my system.

**Comment by takluyver** [comment]
In my system, both `library()` and `help(package = "stats")` show up in the pager - the area that pops up from the bottom of the notebook. Other help output, like `help(lm)` shows up as HTML in the notebook.

**Comment by izahn** [comment]
Interesting. I don't get anything in the `pager` div. I don't get any errors or warnings in the terminal where I started `jupyter notebook`. Looking at the console log in my browser I see some errors about "Couldn't process kernel message...`. Full error messages below in case it helps. Any ideas for debugging further?

```
loaded custom.js
default.js:48 Default extension for cell metadata editing loaded.
rawcell.js:82 Raw Cell Format toolbar preset loaded.
slideshow.js:43 Slideshow extension for metadata editing loaded.
menubar.js:240 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...MenuBar.bind_events @ menubar.js:240
utils.js:59 load_extensions Arguments[1]
session.js:54 Session: kernel_created (0e2eb8e0-0c92-489d-b1f4-608b3ba8db07)
kernel.js:453 Starting WebSockets: ws://localhost:8888/api/kernels/a561e1e8-9a72-441f-8946-7ef9b8b17083
utils.js:36 Loading extension: jupyter-js-widgets/extension
kernel.js:100 Kernel: kernel_connected (a561e1e8-9a72-441f-8946-7ef9b8b17083)
extension.js:89loaded widgets
kernel.js:100 Kernel: kernel_ready (a561e1e8-9a72-441f-8946-7ef9b8b17083)
manager.js:39Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at http://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20161114211402:189:37
manager.js:115Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.(…)(anonymous function) @ manager.js:115
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
```

**Comment by takluyver** [comment]
Hmmm, nothing springs to mind. Do you have the latest version of `notebook`, which is currently 4.2.3?

**Comment by izahn** [comment]
Indeed I do:
```
~ $ jupyter notebook --version
4.2.3
```
I fiddled around (generated a default config file, cleared browser cache) and now I get `help("mean")` showing in the pager. But `help(package = "stats")` still gives me nothing.

**Comment by takluyver** [comment]
Still with the same errors in the JS console? Or something different?

**Comment by izahn** [comment]
I still get the javascript errors. When I first start the notebook I see

```js
loaded custom.js
default.js:48 Default extension for cell metadata editing loaded.
rawcell.js:82 Raw Cell Format toolbar preset loaded.
slideshow.js:43 Slideshow extension for metadata editing loaded.
menubar.js:240 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...MenuBar.bind_events @ menubar.js:240
utils.js:59 load_extensions Arguments[1]
session.js:54 Session: kernel_created (10bd485f-df82-4506-913f-170b82eca513)
kernel.js:453 Starting WebSockets: ws://localhost:8888/api/kernels/348037ff-3b71-4443-8fc3-67d2ca9ed7ea
utils.js:36 Loading extension: jupyter-js-widgets/extension
kernel.js:100 Kernel: kernel_connected (348037ff-3b71-4443-8fc3-67d2ca9ed7ea)
extension.js:89loaded widgets
kernel.js:100 Kernel: kernel_ready (348037ff-3b71-4443-8fc3-67d2ca9ed7ea)
manager.js:39Uncaught (in promise) TypeError: Cannot convert undefined or null to object(…)
manager.js:115Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.(…)(anonymous function) @ manager.js:115
```

Then when I try running a cell containing `help(package = "stats")` I see this error:
```js
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
```

**Comment by takluyver** [comment]
That's not a terribly helpful traceback, but I suspect that the error is really coming from [here](https://github.com/jupyter/notebook/blob/4.2.3/notebook/static/notebook/js/pager.js#L94).

Can you try attaching another listener to that event in the browser's JS console:

```js
Jupyter.notebooks.events.on('open_with_text.Pager', function (event, payload) {
  console.log(payload)
});
```

And see what shows up the next time you it fails?

**Comment by izahn** [comment]
I ran

```js
Jupyter.notebook.events.on('open_with_text.Pager', function (event, payload) {
  console.log(payload)
});
init[1]0: EventsjQuery203060425378129891730.24078677490664258: 7__proto__: Objectconstructor: ()arguments: (...)caller: (...)length: 0name: "Events"prototype: Objectconstructor: ()arguments: (...)caller: (...)length: 0name: "Events"prototype: Object__proto__: ()[[FunctionLocation]]: events.js:15[[Scopes]]: Scopes[1]__proto__: Object__proto__: ()[[FunctionLocation]]: events.js:15[[Scopes]]: Scopes[1]__proto__: Objectlength: 1__proto__: Object[0]
```
in the javascript console, and ran the code cell again. The error looks the same:
```js
kernel.js:916 Couldn't process kernel message TypeError: Cannot read property 'text/html' of undefined
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:28527:29)
    at Events.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:10006)
    at Events.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:6789)
    at Object.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:9131)
    at Events.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14836)
    at Function.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:4575)
    at init.each (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:1626)
    at init.trigger (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:88:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:21710:21)
    at i (http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d:87:5488)(anonymous function) @ kernel.js:916
```

**Comment by takluyver** [comment]
:-(

Do you have time to set up a [development environment](http://jupyter-notebook.readthedocs.io/en/latest/contributing.html) for the notebook and try sticking some `console.log()` statements into the code that's failing?

**Comment by izahn** [comment]
I'll give it a try tomorrow. Thanks for all your help so far!

**Comment by izahn** [comment]
OK, I think I see where it goes wrong, I think @takluyver was right that the problem is in https://github.com/jupyter/notebook/blob/4.2.3/notebook/static/notebook/js/pager.js#L94

When I run `help("mean")` (the case that works) `payload` looks like this:

![image](https://cloud.githubusercontent.com/assets/321235/20313297/78a99126-ab24-11e6-8246-8e398b391bcd.png)

when I run `help(package = "stats")` (the case that does not work) `payload` looks like this:
![image](https://cloud.githubusercontent.com/assets/321235/20313453/ff4cdb20-ab24-11e6-8bd6-74034bbbb8c3.png)

The code in https://github.com/jupyter/notebook/blob/4.2.3/notebook/static/notebook/js/pager.js#L94 expects `payload` to have a `data` attribute`, i.e., it calls

```js
 if (payload.data['text/html'] && payload.data['text/html'] !== "")
```

This fails because (I think) `payload` has no `data` attribute. Setting a break point in that function and running `payload.data['text/html'] ` produces this error:

```js
payload.data['text/html']
VM559:1 Uncaught TypeError: Cannot read property 'text/html' of undefined
    at eval (eval at evaluate (:117:21), <anonymous>:1:13)
    at window._Events.<anonymous> (http://localhost:8888/static/notebook/js/built/1.main.min.js:34203:14)
    at window._Events.dispatch (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:5:10006)
    at window._Events.y.handle (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:5:6789)
    at Object.trigger (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:5:9131)
    at window._Events.<anonymous> (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:5:14836)
    at Function.each (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:4:4575)
    at init.each (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:4:1626)
    at init.trigger (http://localhost:8888/static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd:5:14812)
    at CodeCell._open_with_pager (http://localhost:8888/static/notebook/js/built/1.main.min.js:30147:22)
```
which is the same error message caught later by `Kernel.prototype._handle_ws_message` in kernel.js.

If that really is the problem I have no idea why or how this works for you and not for me...

**Comment by takluyver** [comment]
I think I've found it - #423. And embarrassingly, it was working for me because my installation was of an older version...
