### ISSUE TITLE
`IRkernel::installspec()` returns exit code 1

### ISSUE THREAD

**Issue by cgjosephlee** [IRkernel/IRkernel#581]
I'm trying to instal IRkernel on a server of Ubuntu 16.04.4 LTS without root privilege. Installing dependent packages is successful, until the `IRkernel::installspec()` step.
```{R}
> IRkernel::installspec()
Error in IRkernel::installspec() :
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1.
```
and running
```{R}
> system('jupyter kernelspec --version')
Traceback (most recent call last):
  File "/home/hhl/miniconda3/bin/jupyter-kernelspec", line 6, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/hhl/miniconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/hhl/miniconda3/lib/python3.6/site-packages/zmq/backend/cython/utils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zmq_curve_public
```
but running in zsh shell is good
```
$ jupyter kernelspec --version
5.2.3
```
R session
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.4
```
Seems to be a trouble with zmq package?
I have installed zmq by `conda install zeromq`.
Would anyone please help me to proceed?

**Comment by flying-sheep** [comment]
i’m not entirely surprised that conda still has linking problems.

weird that it works in one and not the other! that has to mean that the environment variables are different.

do you start R from the shell or by clicking an icon? because in the latter case there might be some env variables being set in `.zshrc` that don’t get set when you directly start R in your terminal emulator.

**Comment by cgjosephlee** [comment]
Yes, all the commands were ran under command line.

Here `system('echo $PATH')`, `system('which jupyter')` and `system('jupyter --version')` in R returns same results with shell, but any jupyter subcommands (e.q. `system('jupyter notebook --version')` and others) returns same error as reported above.

Any other informations I can provide?

**Comment by flying-sheep** [comment]
no, this was really helpful. hmm, i can’t really suggest anything except for:

1. purge miniconda and all its packages
2. install everything with pip (or try reinstalling miniconda)

**Comment by rossmounce** [comment]
I also have this exact problem.

I install jupyter via the pipenv route as detailed here:
https://matthewbrown.io/2018/05/05/setting-up-my-python-workspace-2018/

`system('jupyter notebook --version')` returns a similar (but not quite same as reported above:

```
> system('which jupyter')
/home/ross/.local/bin/jupyter
> system('jupyter --version')
4.0.2
> system('jupyter notebook --version')
Traceback (most recent call last):
  File "/home/ross/.local/bin/jupyter-notebook", line 3, in <module>
    from notebook.notebookapp import main
  File "/home/ross/.local/lib/python2.7/site-packages/notebook/notebookapp.py", line 32, in <module>
    from zmq.eventloop import ioloop
  File "/home/ross/.local/lib/python2.7/site-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/home/ross/.local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/home/ross/.local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/home/ross/.local/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/ross/.local/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.1: cannot open shared object file: No such file or directory
```

Outside of R in normal shell... it just needs sudo to return a response:

```
sudo -H jupyter kernelspec --version
[sudo] password for ross: 
5.2.3
```

Would it be possible for `IRkernel::installspec()` to support `sudo -H` ? Would that fix my problem?

**Comment by flying-sheep** [comment]
well, you also have to fix your zmq installation. either you don’t have libzmq itself installed on your OS or the python package links to a version that isn’t (or no longer) present on your system…

**Comment by onlinematters** [comment]
Wow - I have exactly this problem on Windows - right down to the output shown by rossmounce (in my case from jupyter-kernelspec --version command at the Windows command shell prompt).

DId anyone finally solve this?  And if it is a zmq issue, what do I have to do to install libzmq?  Is that a Linux package or a python package?

**Comment by flying-sheep** [comment]
pbdZMQ only use the system libzmq when it is installed, which will probably never be the case on windows. there, it will use the bundled libzmq.

if it really tried to open `libzmq.so.1`, something is seriously wrong. libraries on windows aren’t named `.so`, they’re `.dll`.

**Comment by onlinematters** [comment]
My mistake - the output wasn't exactly the same.  Here is the exact response.  I've looked in the files where the issue is as far as which dll it isn't finding, but can't see where the call is made.  Any further thoughts?

```
> > > system('jupyter kernelspec --version')
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\Scripts\jupyter-kernelspec-script.py", line 6, in <module>
>     from jupyter_client.kernelspecapp import KernelSpecApp
>   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
>     from .connect import *
>   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
>     import zmq
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
>     from zmq import backend
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
>     reraise(*exc_info)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
>     raise value
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
>     _ns = select_backend(first)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
>     mod = __import__(name, fromlist=public_api)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
>     from . import (constants, error, message, context,
> ImportError: DLL load failed: The specified module could not be found.
```

**Comment by flying-sheep** [comment]
well, that either means that libzmq isn’t installed on your system or that the zqm python package isn’t installed properly. has nothing to do with IRkernel.
