### ISSUE TITLE
kernel error on windows

### ISSUE THREAD

**Issue by BruceChen2017** [IRkernel/IRkernel#627]
When I want to create R file on jupyter notebook, there is kernel error. Below are error message:  

```pytb
Traceback (most recent call last):
  File "d:\python36\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "d:\python36\lib\site-packages\tornado\gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\python36\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "d:\python36\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "d:\python36\lib\site-packages\tornado\gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "d:\python36\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "d:\python36\lib\site-packages\tornado\gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\python36\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "d:\python36\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "d:\python36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\python36\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "d:\python36\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "d:\python36\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "d:\python36\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "d:\python36\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "d:\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "d:\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified。
```   

R 3.6.0 Window 10  python3.6.5   
I have `R.exe` on the PATH environment i.e "d:\r-3.6.0\bin"

**Comment by flying-sheep** [comment]
weird. can you try this?

1. `jupyter kernelspec list`
2. open the the path that ends in `...\jupyter\kernels\ir` with the explorer and the `kernel.json` in that folder with a text editor
3. edit the first entry of “argv” in that json to contain the full path to the `R.exe`, i.e.

    ```json
    "argv": ["d:\\r-3.6.0\\bin\\r.exe", …
    ```

**Comment by BruceChen2017** [comment]
@flying-sheep Thanks. It works. Because I update `r` to newer version,but full path in `kernel.json` is not updated automatically.

**Comment by flying-sheep** [comment]
Great! I guess in your case, just re-running `IRkernel::installspec()` would have been sufficient then.

**Comment by abrigandi** [comment]
Bruce, I have the same problem.  Don't want to edit in case I mess up.  Looking for a way to remove R kernel and then reinstall with conda command

**Comment by flying-sheep** [comment]
I don’t know if the kernel.json is part of the conda package, but if not, IRkernel::installspec() should fix it.

**Comment by abrigandi** [comment]
Where do I run IRkernel/IRkernel?
I have anaconda 3 installed on Windows10

Many Thanks

**Comment by flying-sheep** [comment]
?
